Portfolioform website
stevenmukama/Mobile-portfolio pull request #2
Opened 2022-11-01 15:26 UTC by stevenmukama

Added form to the portfolio website.
Added  CSS styles to the form.

2022-11-01 17:12 UTC, christianbiring1 requested changes
Hi @stevenmukama , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# REQUEST CHANGES :recycle: 
![almost](https://user-images.githubusercontent.com/97100091/199294229-c8edcc22-b369-4e67-b4c5-856ab77608b3.gif)


## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary`

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-01 17:12 UTC, christianbiring1 commented on index.html
> +                <div class="listproject">
- [ ] Kindly make sure the page width at all levels fits the screen size.
Your design :point_down: 
![Screenshot from 2022-11-01 18-48-12](https://user-images.githubusercontent.com/97100091/199290521-ce1ca0b7-8bd5-4828-bea7-39aa13b6d025.png)

2022-11-01 17:12 UTC, christianbiring1 commented on index.html
> +                    </li>
- [ ] The button tag inside the list doesn't have any semantic meaning here. Kindly remove that.
`You can check` [here](https://www.w3schools.com/tags/tag_button.asp) `when to use a button`

2022-11-01 17:12 UTC, christianbiring1 commented on index.html
> +                            <ul><button type="button" class="button8"> Ruby</button></ul>
- [ ] The button tag inside the list doesn't have any semantic meaning here. Kindly remove that.

2022-11-01 17:12 UTC, christianbiring1 commented on index.html
> +                    </li>
- [ ] The button tag inside the list doesn't have any semantic meaning here. Kindly remove that.

2022-11-01 17:12 UTC, christianbiring1 commented on index.html
> +                </li>
- [ ] The button tag inside the list doesn't have any semantic meaning here. Kindly remove that.

2022-11-01 17:12 UTC, christianbiring1 commented on index.html
> +                </li>
- [ ] The button tag inside the list doesn't have any semantic meaning here. Kindly remove that.

2022-11-01 17:12 UTC, christianbiring1 commented on index.html
> +                </li>
- [ ] The button tag inside the list doesn't have any semantic meaning here. Kindly remove that.

2022-11-01 17:12 UTC, christianbiring1 commented on index.html
> +                </li>
- [ ] The button tag inside the list doesn't have any semantic meaning here. Kindly remove that.

2022-11-01 17:12 UTC, christianbiring1 commented on index.html
> +                        </li>
- [ ] Kindly make sure you use semantic tag following the Web3C standard.
`It's supposed to be:`
`<ul>`
    `<li>JavaScript</li>`
     `<li>Ruby</li>`
`</ul>`
`And not the other way around. Please consider changing that.`

2022-11-01 17:12 UTC, christianbiring1 commented on index.html
> +                </li>
- [ ] Kindly make sure you use semantic tag following the Web3C standard.
`It's supposed to be:`
`<ul>`
    `<li>JavaScript</li>`
     `<li>Ruby</li>`
`</ul>`
`And not the other way around. Please consider changing that.`

2022-11-01 17:12 UTC, christianbiring1 commented on style.css
> +
- [ ] Kindly make sure your page doesn't overlap. The width is supposed to fits in the screen size.
Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/199293492-7950ab67-13ba-4b99-937a-3527ba6d2140.png)
![image](https://user-images.githubusercontent.com/97100091/199293815-bb50db30-018f-4cfd-96f3-4f3e95fb6d78.png)

Figma template :point_down: 
![image](https://user-images.githubusercontent.com/97100091/199293631-82b9ffda-fb65-44f5-812f-a2a27ab8deeb.png)

2022-11-02 18:15 UTC, frank1738 approved these changes
Hi @stevenmukama , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ README is okay

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 06:53 UTC, merged